services:
  - type: web
    name: strapi-ws
    env: node
    plan: free
    region: frankfurt
    buildCommand: yarn install && yarn build
    startCommand: yarn run develop --watch-admin
    healthCheckPath: /_health
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: strapi-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true

databases:
  - name: strapi-db
    plan: free
    region: frankfurt
